Models/ViewModels/CiudadanosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Miranda_ElOjo.Models.ViewModels
{
    public class CiudadanosViewModel
    {
        public int IdCiu { get; set; }

        public int DniCiu { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Nombre")]
        public string NomCiu { get; set; }

        [Required]
        [StringLength(50)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string EmailCiu { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Telefono")]
        public string TelfCiu { get; set; }

        [Required]
        [Display(Name = "Fecha Nacimiento")]
        public DateTime FechCreacion { get; set; }
    }
}

Models/ciudadanos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miranda_ElOjo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudadanos
    {
        public int IdCiu { get; set; }
        public Nullable<int> DniCiu { get; set; }
        public string NomCiu { get; set; }
        public string EmailCiu { get; set; }
        public string TelfCiu { get; set; }
        public Nullable<System.DateTime> FechCreacion { get; set; }
    }
}

Controllers/CiudadanosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Miranda_ElOjo.Models;
using Miranda_ElOjo.Models.ViewModels;
using System.Data.SqlClient;

namespace Miranda_ElOjo.Controllers
{
    public class CiudadanosController : Controller
    {

        // GET: Ciudadanos
        public ActionResult Index()
        {
            List<ListCiudadanosViewModel> lst;
            using (db_mirandaEntities db = new db_mirandaEntities())
            {
                lst = (from d in db.ciudadanos
                           select new ListCiudadanosViewModel
                           {
                               IdCiu = d.IdCiu,
                               DniCiu = (int)d.DniCiu,
                               NomCiu = d.NomCiu,
                               EmailCiu = d.EmailCiu,
                               TelfCiu = d.TelfCiu
                           }).ToList();
            }
            return View(lst);
        }
        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(CiudadanosViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (db_mirandaEntities db = new db_mirandaEntities())
                    {
                        var oCiudadanos = new ciudadanos();
                        oCiudadanos.DniCiu = model.DniCiu;
                        oCiudadanos.NomCiu = model.NomCiu;
                        oCiudadanos.EmailCiu = model.EmailCiu;
                        oCiudadanos.TelfCiu = model.TelfCiu;

                        db.ciudadanos.Add(oCiudadanos);
                        db.SaveChanges();
                    }
                    return Redirect("~/Ciudadanos/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int Id)
        {
            CiudadanosViewModel model = new CiudadanosViewModel();
            using (db_mirandaEntities db = new db_mirandaEntities())
            {
                var oCiudadanos = db.ciudadanos.Find(Id);
                model.DniCiu= (int)oCiudadanos.DniCiu;
                model.NomCiu = oCiudadanos.NomCiu;
                model.EmailCiu = oCiudadanos.EmailCiu;
                model.TelfCiu = oCiudadanos.TelfCiu;
                model.IdCiu = oCiudadanos.IdCiu;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(CiudadanosViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (db_mirandaEntities db = new db_mirandaEntities())
                    {
                        var oCiudadanos = db.ciudadanos.Find(model.IdCiu);
                        oCiudadanos.DniCiu = model.DniCiu;
                        oCiudadanos.NomCiu = model.NomCiu;
                        oCiudadanos.EmailCiu = model.EmailCiu;
                        oCiudadanos.TelfCiu = model.TelfCiu;
                        
                        db.Entry(oCiudadanos).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Ciudadanos/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            CiudadanosViewModel model = new CiudadanosViewModel();
            using (db_mirandaEntities db = new db_mirandaEntities())
            {
                var oCiudadanos = db.ciudadanos.Find(Id);
                db.ciudadanos.Remove(oCiudadanos);
                db.SaveChanges();
            }
            return Redirect("~/Ciudadanos/");
        }
    }
}

Views/Ciudadanos/Editar.cshtml
@model Miranda_ElOjo.Models.ViewModels.CiudadanosViewModel

@{
    ViewBag.Title = "Nuevo Ciudadano";
}

<h2>@ViewBag.Title</h2>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/Home/index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Admin Ciudadanos
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="/Ciudadanos/index">CRUD de Ciudadanos</a>
                            <a class="nav-link" href="~/Ciudadanos/Nuevo">Agregar Nuevo Ciudadano</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Admin de Dias
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link" href="/Dias/index">CRUD de Dias</a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logueado como:</div>
                Wanda-Vision
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Editar Ciudadano</h3></div>
                            <div class="card-body">
                                @using (Html.BeginForm("Editar", "Ciudadanos", FormMethod.Post))
                                {
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            @Html.HiddenFor(d => d.IdCiu)
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputLastName">DNI</label>
                                                @Html.TextBoxFor(d => d.DniCiu, "", new { @class = "form-control py-4" })
                                                @Html.ValidationMessageFor(d => d.DniCiu, null, new { @class = "red" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputLastName">Nombre</label>
                                                @Html.TextBoxFor(d => d.NomCiu, "", new { @class = "form-control py-4" })
                                                @Html.ValidationMessageFor(d => d.NomCiu, null, new { @class = "red" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="inputEmailAddress">Email</label>
                                        @Html.LabelFor(d => d.EmailCiu)
                                        @Html.TextBoxFor(d => d.EmailCiu, "", new { @class = "form-control py-4" })
                                        @Html.ValidationMessageFor(d => d.EmailCiu, null, new { @class = "red" })
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="inputConfirmPassword">Telefono</label>
                                        @Html.TextBoxFor(d => d.TelfCiu, "", new { @class = "form-control py-4" })
                                        @Html.ValidationMessageFor(d => d.TelfCiu, null, new { @class = "red" })
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input value="Guardar" type="submit" class="btn btn-primary" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

Views/Ciudadanos/Index.cshtml
@model List<Miranda_ElOjo.Models.ViewModels.ListCiudadanosViewModel>
@{
    ViewBag.Title = "Ciudadanos de East View";
}

<h2 style="text-align:center">@ViewBag.Title</h2>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/Home/index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Admin Ciudadanos
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="/Ciudadanos/index">CRUD de Ciudadanos</a>
                            <a class="nav-link" href="~/Ciudadanos/Nuevo">Agregar Nuevo Ciudadano</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Admin de Dias
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link" href="/Dias/index">CRUD de Dias</a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logueado como:</div>
                Wanda-Vision
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        ACTIVIDADES PARA EL DIA ESPECIFICO
                    </div>
                    <div class="row" style="text-align:right; padding:5px;">
                        <a href="~/Ciudadanos/Nuevo" class="btn btn-primary">Nuevo Ciudadano</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>DNI</th>
                                        <th>Nombre</th>
                                        <th>Email</th>
                                        <th>Telefono</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var oElemento in Model)
                                    {
                                        <tr>
                                            <td>@oElemento.IdCiu</td>
                                            <td>@oElemento.DniCiu</td>
                                            <td>@oElemento.NomCiu</td>
                                            <td>@oElemento.EmailCiu</td>
                                            <td>@oElemento.TelfCiu</td>
                                            <td>
                                                <a class="btn btn-default" href="~/Ciudadanos/Editar/@oElemento.IdCiu">Editar</a>
                                                <a class="btn btn-danger" href="~/Ciudadanos/Eliminar/@oElemento.IdCiu">Eliminar</a>
                                                <a class="btn btn-primary" href="~/Tareas/Index/@oElemento.IdCiu">Tareas</a>
                                                <a class="btn btn-success" href="~/Tareas/Nuevo/@oElemento.IdCiu">Crear Tarea</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

Views/Ciudadanos/Nuevo.cshtml
@model Miranda_ElOjo.Models.ViewModels.CiudadanosViewModel

@{
    ViewBag.Title = "Nuevo Ciudadano";
}

<h2>@ViewBag.Title</h2>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/Home/index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Admin Ciudadanos
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="/Ciudadanos/index">CRUD de Ciudadanos</a>
                            <a class="nav-link" href="~/Ciudadanos/Nuevo">Agregar Nuevo Ciudadano</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Admin de Dias
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link" href="/Dias/index">CRUD de Dias</a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logueado como:</div>
                Wanda-Vision
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Nuevo Ciudadano</h3></div>
                            <div class="card-body">
                                @using (Html.BeginForm("Nuevo", "Ciudadanos", FormMethod.Post))
                                {
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div>
                                                @Html.LabelFor(d => d.DniCiu)
                                                @Html.TextBoxFor(d => d.DniCiu, "", new { @class = "form-control" })
                                                @Html.ValidationMessageFor(d => d.DniCiu, null, new { @class = "red" })
                                            </div>
                                            <div>
                                                @Html.LabelFor(d => d.NomCiu)
                                                @Html.TextBoxFor(d => d.NomCiu, "", new { @class = "form-control" })
                                                @Html.ValidationMessageFor(d => d.NomCiu, null, new { @class = "red" })
                                            </div>
                                            <div>
                                                @Html.LabelFor(d => d.EmailCiu)
                                                @Html.TextBoxFor(d => d.EmailCiu, "", new { @class = "form-control" })
                                                @Html.ValidationMessageFor(d => d.EmailCiu, null, new { @class = "red" })
                                            </div>
                                            <div>
                                                @Html.LabelFor(d => d.TelfCiu)
                                                @Html.TextBoxFor(d => d.TelfCiu, "", new { @class = "form-control" })
                                                @Html.ValidationMessageFor(d => d.TelfCiu, null, new { @class = "red" })
                                            </div>
                                            <br />
                                            <div style="text-align:right">
                                                <input value="Guardar" type="submit" class="btn btn-primary" />
                                            </div>
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>