Models/ViewModels/TareasViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Miranda_ElOjo.Models.ViewModels
{
    public class TareasViewModel
    {
        public int IdTarea{ get; set; }
        public int IdCiu { get; set; }

 
        [StringLength(100)]
        [Display(Name = "Nombre")]
        public string NomCiu { get; set; }

        public int IdDia { get; set; }

        [StringLength(50)]
        [Display(Name = "Dia")]
        public string Dia { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; }
    }
}

Models/tareas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miranda_ElOjo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tareas
    {
        public int IdTarea { get; set; }
        public Nullable<int> IdCiu { get; set; }
        public Nullable<int> Dia { get; set; }
        public string Descripcion { get; set; }
    }
}

Controllers/TareasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Miranda_ElOjo.Models;
using Miranda_ElOjo.Models.ViewModels;
using System.Data.SqlClient;

namespace Miranda_ElOjo.Controllers
{
    public class TareasController : Controller
    {
        //Esto es del gringo
        db_mirandaEntities context = new db_mirandaEntities();

        // GET: Tareas
        public ActionResult Index(int Id)
        {
            SqlParameter[] param = new SqlParameter[]
            {
                new SqlParameter("@IdCiu", Id)
            };
            var data = context.Database.SqlQuery<v_tareas>("Select_tareas_Ciudadano @IdCiu", param).ToList();
            return View(data);
        }

        public ActionResult Editar(int Id)
        {
            TareasViewModel model = new TareasViewModel();
            using (db_mirandaEntities db = new db_mirandaEntities())
            {
                var oTareas = db.v_tareas.Find(Id);
                model.IdTarea = oTareas.IdTarea;
                model.IdCiu = (int)oTareas.IdCiu;
                model.NomCiu = oTareas.NomCiu;
                model.IdDia = oTareas.IdDia;
                model.Dia = oTareas.Dia;
                model.Descripcion = oTareas.Descripcion;
            }

            List<DropDiaViewModel> lst = null;
            using (Models.db_mirandaEntities db = new Models.db_mirandaEntities())
            {
                lst = (from d in db.Dias
                       select new DropDiaViewModel
                       {
                           IdDia = d.IdDia,
                           Dia = d.Dia
                       }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Dia.ToString(),
                    Value = d.IdDia.ToString(),
                    Selected = true
                };
            });

            ViewBag.items = items;

            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(TareasViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (db_mirandaEntities db = new db_mirandaEntities())
                    {
                        var oTareas = db.tareas.Find(model.IdTarea);
                        //oTareas.Dia = model.IdDia;
                        oTareas.Descripcion = model.Descripcion;

                        db.Entry(oTareas).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Tareas/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            TareasViewModel model = new TareasViewModel();
            using (db_mirandaEntities db = new db_mirandaEntities())
            {
                var oTareas = db.tareas.Find(Id);
                db.tareas.Remove(oTareas);
                db.SaveChanges();
            }
            return Redirect("~/Ciudadanos/");
        }

        public ActionResult Nuevo(int Id)
        {
            TareasViewModel model = new TareasViewModel();
            using (db_mirandaEntities db = new db_mirandaEntities())
            {
                var oCiudadanos = db.ciudadanos.Find(Id);
                model.IdCiu = oCiudadanos.IdCiu;
            }

            List<DropDiaViewModel> lst = null;
            using (Models.db_mirandaEntities db = new Models.db_mirandaEntities())
            {
                lst = (from d in db.Dias
                       select new DropDiaViewModel
                       {
                           IdDia = d.IdDia,
                           Dia = d.Dia
                       }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Dia.ToString(),
                    Value = d.IdDia.ToString(),
                    Selected = true
                };
            });

            ViewBag.items = items;
            return View(model);
        }

        [HttpPost]
        public ActionResult Nuevo(TareasViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (db_mirandaEntities db = new db_mirandaEntities())
                    {
                        var oTareas = new tareas();
                        oTareas.IdCiu = model.IdCiu;
                        oTareas.Dia = model.IdDia;
                        oTareas.Descripcion = model.Descripcion;

                        db.tareas.Add(oTareas);
                        db.SaveChanges();
                    }
                    return Redirect("~/Ciudadanos/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

    }
}

Views/Tareas/Editar.cshtml
@model Miranda_ElOjo.Models.ViewModels.TareasViewModel

@{
    ViewBag.Title = "Editar Tarea";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>@ViewBag.Title</h2>


<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/Home/index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Admin Ciudadanos
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="/Ciudadanos/index">CRUD de Ciudadanos</a>
                            <a class="nav-link" href="~/Ciudadanos/Nuevo">Agregar Nuevo Ciudadano</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Admin de Dias
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link" href="/Dias/index">CRUD de Dias</a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logueado como:</div>
                Wanda-Vision
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Editar Tarea</h3></div>
                            <div class="card-body">
                                @using (Html.BeginForm("Editar", "Tareas", FormMethod.Post))
                                {
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            @Html.HiddenFor(d => d.IdTarea)
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputLastName">DNI</label>
                                                @Html.TextBoxFor(d => d.NomCiu, "", new { @class = "form-control py-4" })
                                                @Html.ValidationMessageFor(d => d.NomCiu, null, new { @class = "red" })
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputLastName">Nombre</label>
                                                @Html.DropDownListFor(d => d.IdDia, items, "Seleccione un dia", new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="inputEmailAddress">Descripcion</label>
                                        @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control py-4" })
                                        @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input value="Guardar" type="submit" class="btn btn-primary" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

Views/Tareas/Index.cshtml
@model IEnumerable<Miranda_ElOjo.Models.v_tareas>

@{
    ViewBag.Title = "Lista de Tareas";
}

<h2>Index</h2>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/Home/index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Admin Ciudadanos
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="/Ciudadanos/index">CRUD de Ciudadanos</a>
                            <a class="nav-link" href="~/Ciudadanos/Nuevo">Agregar Nuevo Ciudadano</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Admin de Dias
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link" href="/Dias/index">CRUD de Dias</a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logueado como:</div>
                Wanda-Vision
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        ACTIVIDADES PARA EL DIA ESPECIFICO
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Dia</th>
                                        <th>Descripcion</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.IdTarea)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Dia)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                                            <td>
                                                <a style="color:blue" href="~/Tareas/Editar/@item.IdTarea">Editar</a>
                                                <a style="color:red" href="~/Tareas/Eliminar/@item.IdTarea">Eliminar</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

Views/Tareas/Nuevo.cshtml
@model Miranda_ElOjo.Models.ViewModels.TareasViewModel
@{
    ViewBag.Title = "Nueva Tarea";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>@ViewBag.Title</h2>

<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" href="/Home/index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Admin Ciudadanos
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="/Ciudadanos/index">CRUD de Ciudadanos</a>
                            <a class="nav-link" href="~/Ciudadanos/Nuevo">Agregar Nuevo Ciudadano</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Admin de Dias
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                            <a class="nav-link" href="/Dias/index">CRUD de Dias</a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">Addons</div>
                    <a class="nav-link" href="charts.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Charts
                    </a>
                    <a class="nav-link" href="tables.html">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        Tables
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logueado como:</div>
                Wanda-Vision
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>

            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Nueva Tarea</h3></div>
                            <div class="card-body">
                                @using (Html.BeginForm("Nuevo", "Tareas", FormMethod.Post))
                                {
                                    <div class="row">
                                        <div class="col-md-12">
                                            @Html.HiddenFor(d => d.IdCiu)
                                            <div>
                                                <label class="small mb-1" for="inputLastName">Nombre</label>
                                                @Html.TextBoxFor(d => d.NomCiu, "", new { @class = "form-control" })
                                                @Html.ValidationMessageFor(d => d.NomCiu, null, new { @class = "red" })
                                            </div>
                                            <div>
                                                <label class="small mb-1" for="inputLastName">Dia</label>
                                                @Html.DropDownListFor(d => d.IdDia, items, "Seleccione un dia", new { @class = "form-control" })

                                                @Html.ValidationMessageFor(d => d.IdDia, null, new { @class = "red" })
                                            </div>
                                            <div>
                                                <label class="small mb-1" for="inputLastName">Descripcion</label>
                                                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                                                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
                                            </div>
                                            <br />
                                            <div style="text-align:right">
                                                <input value="Guardar" type="submit" class="btn btn-primary" />
                                            </div>
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

@using (Html.BeginForm("Nuevo", "Tareas", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.IdCiu)
            <div>
                @Html.LabelFor(d => d.NomCiu)
                @Html.TextBoxFor(d => d.NomCiu, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.NomCiu, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.IdDia)
                @Html.TextBoxFor(d => d.IdDia, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.IdDia, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>

            <br />
            <div style="text-align:right">
                <input value="Guardar" type="submit" class="btn btn-primary" />
            </div>
        </div>
    </div>

}